<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CourseSeeder extends Seeder
{
    public function run(): void
    {
        $courses = [
            [
                'title' => 'Complete Web Development Bootcamp 2024',
                'slug' => 'complete-web-development-bootcamp-2024',
                'description' => 'Learn HTML, CSS, JavaScript, React, Node.js and more! Build real-world projects and become a full-stack developer.',
                'short_description' => 'Master web development from scratch to advanced concepts',
                'image' => 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-4.0.3&auto=format&fit=crop&w=2069&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example1',
                'category_id' => 1,
                'instructor_id' => 1,
                'level' => 'Beginner',
                'duration' => '6.5 hours',
                'lessons_count' => 45,
                'students_count' => 1250,
                'rating' => 4.8,
                'reviews_count' => 1250,
                'price' => 89.99,
                'original_price' => 199.99,
                'is_free' => false,
                'is_featured' => true,
                'is_popular' => true,
                'is_new' => true,
                'tags' => json_encode(['HTML', 'CSS', 'JavaScript', 'React', 'Node.js']),
                'requirements' => json_encode(['Basic computer knowledge', 'No programming experience required']),
                'what_you_learn' => json_encode(['Build responsive websites', 'Create web applications', 'Deploy to production'])
            ],
            [
                'title' => 'Python for Data Science & Machine Learning',
                'slug' => 'python-data-science-machine-learning',
                'description' => 'Master Python programming for data analysis, visualization, and machine learning with hands-on projects.',
                'short_description' => 'Learn Python for data science and ML',
                'image' => 'https://images.unsplash.com/photo-1526379095098-d400fd0bf935?ixlib=rb-4.0.3&auto=format&fit=crop&w=2074&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example2',
                'category_id' => 4,
                'instructor_id' => 2,
                'level' => 'Intermediate',
                'duration' => '8.2 hours',
                'lessons_count' => 38,
                'students_count' => 980,
                'rating' => 4.9,
                'reviews_count' => 980,
                'price' => 79.99,
                'original_price' => 149.99,
                'is_free' => false,
                'is_featured' => true,
                'is_popular' => true,
                'is_new' => false,
                'tags' => json_encode(['Python', 'Data Science', 'Machine Learning', 'Pandas', 'NumPy']),
                'requirements' => json_encode(['Basic Python knowledge', 'Mathematics fundamentals']),
                'what_you_learn' => json_encode(['Data analysis', 'Machine learning models', 'Data visualization'])
            ],
            [
                'title' => 'Mobile App Development with Flutter',
                'slug' => 'mobile-app-development-flutter',
                'description' => 'Build cross-platform mobile apps with Flutter framework and Dart programming language.',
                'short_description' => 'Create mobile apps with Flutter',
                'image' => 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example3',
                'category_id' => 2,
                'instructor_id' => 8,
                'level' => 'Advanced',
                'duration' => '10.5 hours',
                'lessons_count' => 52,
                'students_count' => 750,
                'rating' => 4.7,
                'reviews_count' => 750,
                'price' => 99.99,
                'original_price' => 179.99,
                'is_free' => false,
                'is_featured' => false,
                'is_popular' => false,
                'is_new' => false,
                'tags' => json_encode(['Flutter', 'Dart', 'Mobile Development', 'iOS', 'Android']),
                'requirements' => json_encode(['Basic programming knowledge', 'Understanding of OOP']),
                'what_you_learn' => json_encode(['Build mobile apps', 'Cross-platform development', 'App store deployment'])
            ],
            [
                'title' => 'UI/UX Design Masterclass',
                'slug' => 'ui-ux-design-masterclass',
                'description' => 'Learn modern design principles, tools, and techniques to create beautiful user interfaces.',
                'short_description' => 'Master UI/UX design principles',
                'image' => 'https://images.unsplash.com/photo-1561070791-2526d30994b5?ixlib=rb-4.0.3&auto=format&fit=crop&w=764&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example4',
                'category_id' => 3,
                'instructor_id' => 3,
                'level' => 'Beginner',
                'duration' => '7.8 hours',
                'lessons_count' => 42,
                'students_count' => 620,
                'rating' => 4.6,
                'reviews_count' => 620,
                'price' => 69.99,
                'original_price' => 129.99,
                'is_free' => false,
                'is_featured' => false,
                'is_popular' => false,
                'is_new' => true,
                'tags' => json_encode(['UI Design', 'UX Design', 'Figma', 'Adobe XD', 'Prototyping']),
                'requirements' => json_encode(['No design experience required', 'Basic computer skills']),
                'what_you_learn' => json_encode(['Design principles', 'User research', 'Prototyping'])
            ],
            [
                'title' => 'Digital Marketing Fundamentals',
                'slug' => 'digital-marketing-fundamentals',
                'description' => 'Master the basics of digital marketing including SEO, social media, and content marketing.',
                'short_description' => 'Learn digital marketing basics',
                'image' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1115&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example5',
                'category_id' => 6,
                'instructor_id' => 5,
                'level' => 'Beginner',
                'duration' => '5.5 hours',
                'lessons_count' => 35,
                'students_count' => 890,
                'rating' => 4.5,
                'reviews_count' => 890,
                'price' => 0.00,
                'original_price' => 99.99,
                'is_free' => true,
                'is_featured' => false,
                'is_popular' => true,
                'is_new' => false,
                'tags' => json_encode(['Digital Marketing', 'SEO', 'Social Media', 'Content Marketing']),
                'requirements' => json_encode(['No experience required', 'Basic internet knowledge']),
                'what_you_learn' => json_encode(['Marketing strategies', 'SEO optimization', 'Social media management'])
            ],
            [
                'title' => 'React.js Complete Guide',
                'slug' => 'react-js-complete-guide',
                'description' => 'Learn React.js from scratch to advanced concepts with real-world projects and best practices.',
                'short_description' => 'Master React.js development',
                'image' => 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example6',
                'category_id' => 1,
                'instructor_id' => 6,
                'level' => 'Intermediate',
                'duration' => '9.2 hours',
                'lessons_count' => 48,
                'students_count' => 1100,
                'rating' => 4.8,
                'reviews_count' => 1100,
                'price' => 84.99,
                'original_price' => 159.99,
                'is_free' => false,
                'is_featured' => false,
                'is_popular' => false,
                'is_new' => false,
                'tags' => json_encode(['React', 'JavaScript', 'Frontend', 'Web Development']),
                'requirements' => json_encode(['Basic JavaScript knowledge', 'HTML/CSS fundamentals']),
                'what_you_learn' => json_encode(['React components', 'State management', 'Hooks'])
            ],
            [
                'title' => 'Cybersecurity Essentials',
                'slug' => 'cybersecurity-essentials',
                'description' => 'Learn the fundamentals of cybersecurity, ethical hacking, and network security.',
                'short_description' => 'Master cybersecurity basics',
                'image' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example7',
                'category_id' => 9,
                'instructor_id' => 7,
                'level' => 'Beginner',
                'duration' => '6.8 hours',
                'lessons_count' => 40,
                'students_count' => 850,
                'rating' => 4.9,
                'reviews_count' => 850,
                'price' => 94.99,
                'original_price' => 169.99,
                'is_free' => false,
                'is_featured' => true,
                'is_popular' => false,
                'is_new' => false,
                'tags' => json_encode(['Cybersecurity', 'Ethical Hacking', 'Network Security', 'Penetration Testing']),
                'requirements' => json_encode(['Basic computer knowledge', 'Network fundamentals']),
                'what_you_learn' => json_encode(['Security principles', 'Vulnerability assessment', 'Security tools'])
            ],
            [
                'title' => 'Machine Learning with Python',
                'slug' => 'machine-learning-python',
                'description' => 'Comprehensive course on machine learning algorithms and their implementation using Python.',
                'short_description' => 'Learn machine learning with Python',
                'image' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=1170&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example8',
                'category_id' => 10,
                'instructor_id' => 9,
                'level' => 'Advanced',
                'duration' => '12.5 hours',
                'lessons_count' => 65,
                'students_count' => 720,
                'rating' => 4.8,
                'reviews_count' => 720,
                'price' => 109.99,
                'original_price' => 189.99,
                'is_free' => false,
                'is_featured' => true,
                'is_popular' => true,
                'is_new' => false,
                'tags' => json_encode(['Machine Learning', 'Python', 'TensorFlow', 'Scikit-learn', 'Deep Learning']),
                'requirements' => json_encode(['Python programming', 'Mathematics fundamentals', 'Statistics basics']),
                'what_you_learn' => json_encode(['ML algorithms', 'Model training', 'Neural networks'])
            ],
            [
                'title' => 'AWS Cloud Practitioner',
                'slug' => 'aws-cloud-practitioner',
                'description' => 'Prepare for AWS Cloud Practitioner certification with hands-on labs and real-world scenarios.',
                'short_description' => 'AWS Cloud Practitioner certification',
                'image' => 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1172&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example9',
                'category_id' => 8,
                'instructor_id' => 10,
                'level' => 'Beginner',
                'duration' => '8.0 hours',
                'lessons_count' => 45,
                'students_count' => 680,
                'rating' => 4.6,
                'reviews_count' => 680,
                'price' => 74.99,
                'original_price' => 139.99,
                'is_free' => false,
                'is_featured' => false,
                'is_popular' => false,
                'is_new' => false,
                'tags' => json_encode(['AWS', 'Cloud Computing', 'Certification', 'DevOps']),
                'requirements' => json_encode(['Basic IT knowledge', 'No AWS experience required']),
                'what_you_learn' => json_encode(['AWS services', 'Cloud concepts', 'Security best practices'])
            ],
            [
                'title' => 'JavaScript Fundamentals',
                'slug' => 'javascript-fundamentals',
                'description' => 'Learn JavaScript from the ground up with practical examples and real-world projects.',
                'short_description' => 'Master JavaScript basics',
                'image' => 'https://images.unsplash.com/photo-1627398242454-45a1465c2479?ixlib=rb-4.0.3&auto=format&fit=crop&w=1174&q=80',
                'video_url' => 'https://www.youtube.com/watch?v=example10',
                'category_id' => 7,
                'instructor_id' => 4,
                'level' => 'Beginner',
                'duration' => '5.5 hours',
                'lessons_count' => 32,
                'students_count' => 950,
                'rating' => 4.7,
                'reviews_count' => 950,
                'price' => 49.99,
                'original_price' => 99.99,
                'is_free' => false,
                'is_featured' => false,
                'is_popular' => false,
                'is_new' => true,
                'tags' => json_encode(['JavaScript', 'ES6', 'DOM', 'Async Programming']),
                'requirements' => json_encode(['Basic HTML knowledge', 'No programming experience required']),
                'what_you_learn' => json_encode(['JavaScript syntax', 'DOM manipulation', 'Async programming'])
            ]
        ];

        foreach ($courses as $course) {
            DB::table('courses')->insert($course);
        }
    }
}
